product-name: harbor-container-registry
network-properties:
  singleton_availability_zone:
    name: ((AZ_1))
  other_availability_zones:
  - name: ((AZ_1))
  - name: ((AZ_2))
  - name: ((AZ_3))
  network:
    name: pks
  service_network:
    name: pks-services
product-properties:
  .properties.hostname:
    value: "harbor.((SUBDOMAIN_NAME)).((DOMAIN_NAME))"
  .properties.admin_password:
    value:
      secret: ((OPSMAN_ADMIN_PASSWD))
  .properties.admin_password_for_smoketest:
    value:
      secret: ((OPSMAN_ADMIN_PASSWD))
  .properties.server_cert_key:
      value:
        cert_pem: ((DOMAIN_CRT))
        private_key_pem: ((DOMAIN_KEY))
  .properties.server_cert_ca:
      value: ((DOMAIN_CA))
resource-config:
  harbor-app:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
